version: '3.8'
services:
  postgres1:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=5 
      -c max_wal_senders=5
    volumes:
      - ./init-orders.sql:/docker-entrypoint-initdb.d/init.sql

  postgres2:
    image: postgres:15
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    command: >
      postgres 
      -c wal_level=logical 
      -c max_replication_slots=5 
      -c max_wal_senders=5
    volumes:
      - ./init-customers.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql

  jobmanager:
    image: flink:1.18.0
    platform: linux/arm64
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./target:/opt/flink/usrlib

  taskmanager:
    image: flink:1.18.0
    platform: linux/arm64
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2